### PR TITLE
change pipelines for version 2.7

### PR DESCRIPTION
**Pull request by ernesgonzalez33**

### CODE REVIEW

**Comment by ernesgonzalez33** [comment]
@mnecas these are the changes here for version 2.7 of the pipeline

**Review by mnecas — APPROVED** [review]

**Comment by ernesgonzalez33** [comment]
@mnecas I need to debug why this is failing all the time. Please don't merge it

**Comment by ernesgonzalez33** [comment]
@mnecas you can merge

**Review by mnecas — APPROVED** [review]

**Pull request merged**
